language: php

php:
    - '7.1.3'
    - '7.2'
    - '7.3'
    - '7.4'

before_script:
    - nvm install 12
    - rm composer.lock
    - composer install
    - yarn install

script:
    - yarn build
    - bin/phpunit
