language: php

php:
    - '7.2'
    - '7.3'
    - '7.4'

before_script:
    - nvm install 12
    - rm composer.lock
    - composer install
    - yarn install

script:
    - bin/build
    - bin/phpunit
