language: php

php:
    - '7.2'
    - '7.3'
    - '7.4'

before_install:
    - composer self-update --2
    - nvm install 12
    - rm composer.lock

install:
    - composer install
    - yarn install

script:
    - vendor/bin/psalm
    - yarn build
    - bin/phpunit --coverage-clover var/coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash) -f var/coverage.xml
