version: "3"

services:
    web:
        image: caddy:latest
        ports:
            - "${MANGA_SERVER_PORT:-8000}:8000"
        volumes:
            - ./:/app
            - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
    app:
        image: manga-server:runtime
        build: .
        volumes:
            - ./:/app
