name: Build

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: ['7.2', '7.4', '8.0']
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
            -   name: Setup NodeJS
                uses: actions/setup-node@v2
                with:
                    node-version: 12
            -   name: Install Composer dependencies
                run: |
                    rm composer.lock
                    composer install --no-progress --prefer-dist --optimize-autoloader
            -   name: Intall yarn dependencies
                run: yarn install
            -   name: Build frontend artifact
                run: |
                    NODE_ENV=production yarn encore production
            -   name: Run Tests
                run: php bin/phpunit --coverage-clover var/coverage.xml
            -   name: Upload coverage to Codecov
                uses: codecov/codecov-action@v1
                with:
                    files: ./var/coverage.xml
